/* Generated By:JavaCC: Do not edit this line. FOParserConstants.java */
package org.uacalc.fol.grammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FOParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FORALL = 5;
  /** RegularExpression Id. */
  int EXISTS = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int AND = 8;
  /** RegularExpression Id. */
  int OR = 9;
  /** RegularExpression Id. */
  int IMPLIES = 10;
  /** RegularExpression Id. */
  int EQ = 11;
  /** RegularExpression Id. */
  int LPAREN = 12;
  /** RegularExpression Id. */
  int RPAREN = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int IDENT = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"all\"",
    "\"exists\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"->\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<IDENT>",
  };

}
